# 운영 서버 설정
application:
  workspace: PROD
  port: 8030

spring:
  config:
    activate:
      on-profile: prod

database:
  url:
  username:
  password:

hikari:
  connection-timeout: 3000
  maximum-pool-size: 30
  max-lifetime: 150000

logging:
  lovel: INFO

firebase:
  path: ""
  key: ""