# 로컬 개발 설정
application:
  workspace: LOCAL
  port: 8006

spring:
  config:
    activate:
      on-profile: local

database:
  url: jdbc:mariadb://52.40.58.201:3306/vmgo
  username: devfuse
  password: fkdlcmdhs0803

hikari:
  connection-timeout: 180
  maximum-pool-size: 2000
  max-lifetime: 3000

logging:
  lovel: DEBUG

firebase:
  path: "src/main/resources/vmgo-4168a-firebase-adminsdk-xnmfs-e10840793e.json"
  key: "AIzaSyAAuwsJKchgm-bwcfVy-sfL69i8tOM4CgQ"



