# 테스트 서버 설정
application:
  workspace: DEV
  port: 8030

spring:
  config:
    activate:
      on-profile: dev

database:
  url: jdbc:mariadb://
  username:
  password:

hikari:
  connection-timeout: 180
  maximum-pool-size: 20
  max-lifetime: 3000

logging:
  lovel: INFO

firebase:
  path: ""
  key: ""