server:
  port: 8006

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/vmgo
    username: root
    password: root
#    username: devfuse
#    password: fkdlcmdhs0803
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 150
      max-lifetime: 1800000
      pool-name: HikariCP
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

#logging:
#  slack:
#    webhook-uri: https://hooks.slack.com/services/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
#  level:
#    org.hibernate:
#      type.descriptor.sql: trace #show parameter binding
#      SQL: DEBUG

